-- 初始化linux命令分类
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (1, '系统信息');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (2, '关机 (系统的关机、重启以及登出 ) ');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (3, '文件和目录');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (4, '文件搜索');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (5, '挂载文件系统');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (6, '磁盘空间');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (7, '用户和群组');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (8, '文件的权限');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (9, '文件的特殊属性');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (10, '压缩及解压文件');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (11, 'RPM包');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (12, 'YUM软件包升级器');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (13, 'DEB包');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (14, 'APT软件工具');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (15, '查看文件内容');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (16, '文本处理');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (17, '字符设置和文件格式转换');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (18, '文件系统分析');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (19, '初始化文件系统');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (20, 'SWAP文件系统');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (21, '备份');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (22, '光盘');
INSERT INTO `ktools`.`kt_cmd_category`(`id`, `name`) VALUES (23, '网络');
